# HTTP Server
[server]
  address = ":8199"
  serverAgent = "glow-admin" # HTTP 响应头 "Server"
  logPath = "./log/server"
  accessLogEnabled  = true # 访问日志
  logStdout = false # 控制台输出日志
  dumpRouterMap    = true # 控制台打印路由map

# Logger. 业务日志 g.Log().Println()
[logger]
  path = "./log/service"
  level = "all"
  stdout = true

# Database
[database]
  link = "mysql:root:root@tcp(127.0.0.1:3306)/glow-admin"
  debug = true
  # Database logger
  [database.logger]
    path = "./log/sql"
    level = "all"
    stdout = true

[gfcli]
  [[gfcli.gen.dao]]
    link = "mysql:root:root@tcp(127.0.0.1:3306)/glow-admin"
    tables = "sys_config,sys_config_data"
    jsonCase = "Snake"